FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install && npm cache clean --force

COPY . .

# Define las variables de entorno
ARG BACKEND_MEDIA_PATHS
ENV BACKEND_MEDIA_PATHS=$BACKEND_MEDIA_PATHS

ARG BACKEND_REVIEWS_URL
ENV BACKEND_REVIEWS_URL=$BACKEND_REVIEWS_URL

ARG GOOGLE_MAPS_PLACE_REVIEWS
ENV GOOGLE_MAPS_PLACE_REVIEWS=$GOOGLE_MAPS_PLACE_REVIEWS

ARG NEXT_PUBLIC_BACKEND_EMAIL_URL
ENV NEXT_PUBLIC_BACKEND_EMAIL_URL=$NEXT_PUBLIC_BACKEND_EMAIL_URL

ARG NEXT_PUBLIC_BACKEND_USERS_URL
ENV NEXT_PUBLIC_BACKEND_USERS_URL=$NEXT_PUBLIC_BACKEND_USERS_URL

ARG NEXT_PUBLIC_SOCKET_CONNECTION
ENV NEXT_PUBLIC_SOCKET_CONNECTIONL=$NEXT_PUBLIC_SOCKET_CONNECTION

ARG GOOGLE_PUB_ID
ENV GOOGLE_PUB_ID=$GOOGLE_PUB_ID

ENV NODE_ENV=production

EXPOSE 3000

CMD npm run deploy
