const texts = {
  ES: {
    navtext1: "Inicio",
    navtext2: "Ubicación",
    navtext3: "Fotos",
    navtext4: "Servicios",
    authtext1: "Cerrar sesión",
    authtext2: "Iniciar sesión",
    accountmenutext1: "Mi cuenta",
    accountmenutext2: "Ajustes",
    accountmenutext3: "Configuracíon de la cuenta",
    backbuttontext1: "Volver",
    tabmenutitle1: "Notas",
    tabmenutitle2: "Reservas",
    tabmenutitle3: "Pagos",
    tabmenutextalert1: "Aún no tienes reservas.",
    reviewplaceholdertext1: "Deja tu comentario…",
    reviewbuttontext1: "Comentar",
    authtoasttext1: "¡Bienvenido/a",
    hometitle1: "Iguazú Urban",
    hometitle2: "Hotel",
    hometitle3: "Express",
    homedescription1: "Somos un hotel moderno con todos los servicios para que puedas disfrutar unos días únicos en Puerto Iguazú, Misiones.",
    homebuttontitle1: "Saber más",
    sociallinktitle1: "Síguenos",
    locationtitle1: "Fray Luis Beltrán 290",
    locationtitle2: "Puerto Iguazú - Misiones",
    locationdescription1: "Ubicado en una zona céntrica, cerca de restaurantes, comercios, mercados y la terminal de autobuses.",
    locationbuttontitle1: "Cómo llegar",
    cardimgtext1: "Desayuno",
    cardimgtext2: "Habitaciones",
    cardimgtext3: "Pileta",
    cardimgtext4: "Iguazú",
    sectiontitle1: "Galería de Fotos",
    sectiontitle2: "Servicios del Hotel",
    servicetext1: [{t:"Habitaciones", d:"Dobles y Triples"}, {t:"Desayuno",d:"Incluido"}, {t:"Piscina",d:"y Solarium"}, {t:"Avenida principal",d:"a 200 mts"}],
    servicetext2: [{t:"WIFI", d:"Gratuito"}, {t:"Recepción",d:"24 hs"}, {t:"Terminal de Ómnibus",d:"a 300 mts"}, {t:"Hito 3 Fronteras",d:"a 1200 mts"}],
    testimonialtext1: "Lo que dicen nuestros clientes",
    jointitle1: "Tu viaje",
    jointitle2: "comienza aquí",
    jointext1 : "Manténgase actualizado con nuestra última información y viajes.",
    joinplaceholder1: "Introduce tu correo electrónico",
    joinbuttontext1: "Suscríbete a nuestro boletín",
    joinsuccess: "Gracias por tu suscripción:",
    footertitle1: "Siguenos",
    footertitle2: "Dirección",
    footertitle3: "Contacto",
    footertitle4: "Más Información",
    footerinfo1: "Fray Luis Beltrán 290, Iguazú - Misiones",
    footerinfo2: "+54 3757 - 458904",
    footerinfo3: "Iguazuurbanhotel@gmail.com",
    footerinfo4: "Parque Nacional Iguazú",
    footerinfo5: "Parque Nacional do Iguazú (Brasil)",
    footerinfo6: "Documentación para ingresar a Brasil (DNM)",
    footerinfo7: "Aeropuerto Iguazú",
    footerinfo8: "Paseo de Luna llena en Cataratas del Iguazú"
  },
  US: {
    navtext1: "Home",
    navtext2: "Location",
    navtext3: "Photos",
    navtext4: "Services",
    authtext1: "Logout",
    authtext2: "Login",
    accountmenutext1: "My Account",
    accountmenutext2: "Settings",
    accountmenutext3: "Account Settings",
    backbuttontext1: "Back",
    tabmenutitle1: "Notes",
    tabmenutitle2: "Reservations",
    tabmenutitle3: "Payments",
    tabmenutextalert1: "You don't have any reservations yet.",
    reviewplaceholdertext1: "Leave your comment...",
    reviewbuttontext1: "Comment",
    authtoasttext1: "Welcome",
    hometitle1: "Iguazú Urban",
    hometitle2: "Hotel",
    hometitle3: "Express",
    homedescription1: "We are a modern hotel with all the services for you to enjoy unique days in Puerto Iguazú, Misiones.",
    homebuttontitle1: "Learn more",
    sociallinktitle1: "Follow us",
    locationtitle1: "Fray Luis Beltrán 290",
    locationtitle2: "Puerto Iguazú - Misiones",
    locationdescription1: "Located in a central area, close to restaurants, shops, markets, and the bus terminal.",
    locationbuttontitle1: "How to get there",
    cardimgtext1: "Breakfast",
    cardimgtext2: "Rooms",
    cardimgtext3: "Pool",
    cardimgtext4: "Iguazú",
    sectiontitle1: "Photo Gallery",
    sectiontitle2: "Hotel Services",
    servicetext1: [{t:"Rooms", d:"Double and Triple"}, {t:"Breakfast",d:"Included"}, {t:"Pool",d:"and Solarium"}, {t:"Main avenue",d:"200 meters away"}],
    servicetext2: [{t:"WIFI", d:"Free"}, {t:"Reception",d:"24 hours"}, {t:"Bus Terminal",d:"300 meters away"}, {t:"Three Borders Landmark",d:"1200 meters away"}],
    footertitle1: "Follow us",
    footertitle2: "Address",
    footertitle3: "Contact",
    footertitle4: "More Information",
    footerinfo1: "Fray Luis Beltrán 290, Iguazú - Misiones",
    footerinfo2: "+54 3757 - 458904",
    footerinfo3: "Iguazuurbanhotel@gmail.com",
    footerinfo4: "Iguazú National Park",
    footerinfo5: "Iguazú National Park (Brazil)",
    footerinfo6: "Documentation to enter Brazil (DNM)",
    footerinfo7: "Iguazú Airport",
    footerinfo8: "Full Moon Tour at Iguazú Falls"
  },
  BR: {
    navtext1: "Início",
    navtext2: "Localização",
    navtext3: "Fotos",
    navtext4: "Serviços",
    authtext1: "Sair",
    authtext2: "Entrar",
    accountmenutext1: "Minha conta",
    accountmenutext2: "Configurações",
    accountmenutext3: "Configuração da conta",
    backbuttontext1: "Voltar",
    tabmenutitle1: "Notas",
    tabmenutitle2: "Reservas",
    tabmenutitle3: "Pagamentos",
    tabmenutextalert1: "Você ainda não tem reservas.",
    reviewplaceholdertext1: "Deixe seu comentário...",
    reviewbuttontext1: "Comentar",
    authtoasttext1: "Bem-vindo/a",
    hometitle1: "Iguazú Urban",
    hometitle2: "Hotel",
    hometitle3: "Express",
    homedescription1: "Somos um hotel moderno com todos os serviços para você aproveitar dias únicos em Puerto Iguazú, Misiones.",
    homebuttontitle1: "Saiba mais",
    sociallinktitle1: "Siga-nos",
    locationtitle1: "Fray Luis Beltrán 290",
    locationtitle2: "Puerto Iguazú - Misiones",
    locationdescription1: "Localizado em uma área central, perto de restaurantes, lojas, mercados e da rodoviária.",
    locationbuttontitle1: "Como chegar",
    cardimgtext1: "Café da manhã",
    cardimgtext2: "Quartos",
    cardimgtext3: "Piscina",
    cardimgtext4: "Iguazú",
    sectiontitle1: "Galeria de Fotos",
    sectiontitle2: "Serviços do Hotel",
    servicetext1: [{t:"Quartos", d:"Duplos e Triplos"}, {t:"Café da manhã",d:"Incluído"}, {t:"Piscina",d:"e Solarium"}, {t:"Avenida principal",d:"a 200 mts"}],
    servicetext2: [{t:"WIFI", d:"Gratuito"}, {t:"Recepção",d:"24 hs"}, {t:"Rodoviária",d:"a 300 mts"}, {t:"Marco das Três Fronteiras",d:"a 1200 mts"}],
    footertitle1: "Siga-nos",
    footertitle2: "Endereço",
    footertitle3: "Contato",
    footertitle4: "Mais Informações",
    footerinfo1: "Fray Luis Beltrán 290, Iguazú - Misiones",
    footerinfo2: "+54 3757 - 458904",
    footerinfo3: "Iguazuurbanhotel@gmail.com",
    footerinfo4: "Parque Nacional Iguazú",
    footerinfo5: "Parque Nacional do Iguazú (Brasil)",
    footerinfo6: "Documentação para ingressar no Brasil (DNM)",
    footerinfo7: "Aeroporto de Iguazú",
    footerinfo8: "Passeio de Lua Cheia nas Cataratas do Iguazú"
  },
};

  export default texts;