const texts = {
  ES: {
    navText1: "Inicio",
    navText2: "Ubicación",
    navText3: "Fotos",
    navText4: "Servicios",
    authText1: "Cerrar sesión",
    authText2: "Iniciar sesión",
    accountMenuText1: "Mi cuenta",
    accountMenuText2: "Ajustes",
    accountMenuText3: "Configuración de la cuenta",
    backButtonText1: "Volver",
    tabMenuTitle1: "Notas",
    tabMenuTitle2: "Reservas",
    tabMenuTitle3: "Pagos",
    tabMenuTextAlert1: "Aún no tienes reservas.",
    reviewPlaceholderText1: "Deja tu comentario…",
    reviewButtonText1: "Comentar",
    authToastText1: "¡Bienvenido/a",
    homeTitle1: "Iguazú Urban",
    homeTitle2: "Hotel",
    homeTitle3: "Express",
    homeDescription1: "Somos un hotel moderno con todos los servicios para que puedas disfrutar unos días únicos en Puerto Iguazú, Misiones.",
    homeButtonTitle1: "Saber más",
    socialLinkTitle1: "Síguenos",
    locationTitle1: "Fray Luis Beltrán 290",
    locationTitle2: "Puerto Iguazú - Misiones",
    locationDescription1: "Ubicado en una zona céntrica, cerca de restaurantes, comercios, mercados y la terminal de autobuses.",
    locationButtonTitle1: "Cómo llegar",
    cardImgText1: "Desayuno",
    cardImgText2: "Habitaciones",
    cardImgText3: "Pileta",
    cardImgText4: "Iguazú",
    sectionTitle1: "Galería de Fotos",
    sectionTitle2: "Servicios del Hotel",
    serviceText1: [
      { t: "Habitaciones", d: "Dobles y Triples" },
      { t: "Desayuno", d: "Incluido" },
      { t: "Piscina", d: "y Solarium" },
      { t: "Avenida principal", d: "a 200 mts" }
    ],
    serviceText2: [
      { t: "WIFI", d: "Gratuito" },
      { t: "Recepción", d: "24 hs" },
      { t: "Terminal de Ómnibus", d: "a 300 mts" },
      { t: "Hito 3 Fronteras", d: "a 1200 mts" }
    ],
    testimonialText1: "Lo que dicen nuestros clientes",
    textClose1: "Cerrar",
    joinTitle1: "Tu viaje",
    joinTitle2: "comienza aquí",
    joinText1: "Manténgase actualizado con nuestra última información y viajes.",
    joinPlaceholder1: "Introduce tu correo electrónico",
    joinButtonText1: "Suscríbete a nuestro boletín",
    joinSuccess: "Gracias por tu suscripción:",
    footerTitle1: "Síguenos",
    footerTitle2: "Dirección",
    footerTitle3: "Contacto",
    footerTitle4: "Más Información",
    footerTitle5: "Support",
    footerInfoDirection: "Fray Luis Beltrán 290, Iguazú - Misiones",
    footerInfoPhone: "+54 3757 - 458904",
    footerInfoEmail: "Iguazuurbanhotel@gmail.com",
    footerInfoParkArg: "Parque Nacional Iguazú",
    footerInfoParkBr: "Parque Nacional do Iguazú (Brasil)",
    footerInfoMigrationBr: "Documentación para ingresar a Brasil (DNM)",
    footerInfoAirport: "Aeropuerto Iguazú",
    footerInFullMoon: "Paseo de luna llena en las Cataratas del Iguazú",
    footerInfoFaq: "FAQ",
    footerInfoPolicy: "Política de privacidad",
    footerInfoDeveloper: "Desarrollador"
  }
};

export default texts;
