const index = {
  BREVO_API_KEY: process.env.BREVO_API_KEY,
  BACKEND_EMAIL_URL: process.env.NEXT_PUBLIC_BACKEND_EMAIL_URL,
  BACKEND_REVIEWS_URL: process.env.BACKEND_REVIEWS_URL,
  BACKEND_USERS_URL: process.env.NEXT_PUBLIC_BACKEND_USERS_URL,
  BACKEND_MEDIA_PATHS: process.env.BACKEND_MEDIA_PATHS,
  GOOGLE_MAPS_PLACE_REVIEWS: process.env.GOOGLE_MAPS_PLACE_REVIEWS,
  SOCKET_CONNECTION: process.env.NEXT_PUBLIC_SOCKET_CONNECTION,
  GOOGLE_PUB_ID: process.env.GOOGLE_PUB_ID as string,
}

export default index;