const index = {
  BREVO_API_KEY: "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",
  JWT_SECRET: "secret",
  CLOUDINARY_API_SECRET: "5T3vSJgftf7Prv2QDF6_A9EEPAI",
  CLOUDINARY_API_KEY: "288785968364462",
  CLOUDINARY_CLOUD_NAME: "dgyscrnpp",
  BACKEND_EMAIL_URL: process.env.NEXT_PUBLIC_BACKEND_EMAIL_URL,
  BACKEND_REVIEWS_URL: process.env.BACKEND_REVIEWS_URL,
  BACKEND_USERS_URL: process.env.NEXT_PUBLIC_BACKEND_USERS_URL,
  BACKEND_MEDIA_PATHS: process.env.BACKEND_MEDIA_PATHS,
  GOOGLE_MAPS_PLACE_REVIEWS: process.env.GOOGLE_MAPS_PLACE_REVIEWS,
  SOCKET_CONNECTION: process.env.NEXT_PUBLIC_SOCKET_CONNECTION,
  GOOGLE_PUB_ID: process.env.GOOGLE_PUB_ID as string,
}

export default index;