const index = {
  BACKEND_EMAIL_URL: process.env.NEXT_PUBLIC_BACKEND_EMAIL_URL,
  BACKEND_REVIEWS_URL: process.env.BACKEND_REVIEWS_URL,
  BACKEND_USERS_URL: process.env.NEXT_PUBLIC_BACKEND_USERS_URL,
  BACKEND_MEDIA_PATHS: process.env.BACKEND_MEDIA_PATHS
}

export default index