const index = {
  BACKEND_EMAIL_URL: process.env.NEXT_PUBLIC_BACKEND_EMAIL_URL,
  BACKEND_REVIEWS_URL: process.env.BACKEND_REVIEWS_URL,
  BACKEND_USERS_URL: process.env.NEXT_PUBLIC_BACKEND_USERS_URL,
  BACKEND_MEDIA_PATHS: process.env.BACKEND_MEDIA_PATHS,
  GOOGLE_MAPS_PLACE_REVIEWS: process.env.GOOGLE_MAPS_PLACE_REVIEWS,
}

export default index